name: Build & Deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nodejs App
        uses: appleboy/ssh-action@v0.1.2

        with:
          host: ${{ secrets.SSH_HOST }} # IP address of the server you wish to ssh into
          port: ${{ secrets.SSH_PORT }} # Port of the server you wish to ssh into
          password: ${{secrets.SSH_PASSWORD }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh                

            pm2 stop zuly
            cd zuly
            git pull origin master
            rm -rf node_modules
            yarn
            pm2 start src/zuly.js --name zuly
            exit