name: Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
        runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]
          node: [16]

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      
      - name: Cache node_modules 📦
        uses: actions/cache@v2.1.7
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn
      
      - name: Run ESLint
        run: yarn lint
  deploy:
    name: "Deploy to production"
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: lint
    steps:
      - name: Setup ssh
        run: |
          mkdir -p ~/.ssh/
          echo "$FTP_KEY" > ~/.ssh/key
          chmod 600 ~/.ssh/key
          cat >>~/.ssh/config << END
          Host prod
            HostName $FTP_HOST
            User $FTP_USER
            Port $FTP_PORT
            IdentityFile ~/.ssh/key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.FTP_USER }}
          SSH_KEY: ${{ secrets.FTP_KEY }}
          SSH_HOST: ${{ secrets.FTP_HOST }}
          SSH_PORT: ${{ secrets.FTP_PORT }}
      - name: Stopping bot
        run: ssh prod 'systemctl --user stop zulybot'
      - name: Cloning repository
        run: ssh prod 'cd zulybot && git fetch && git reset --hard origin/main'
      - name: Install dependencies
        run: ssh prod 'bash --login -c "cd zulybot && npm ci"'
      - name: Starting bot
        run: ssh prod 'systemctl --user start zulybot'