name: Build & Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Nodejs App
        uses: appleboy/ssh-action@v0.1.2

        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_PRIVATE_KEY}} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh                

            git clone https://aldhanekaa:${{secrets.GITHUB_TOKEN}}@github.com/zulybot/zuly.git
            cd zuly
            yarn
            yarn forever